### ISSUE TITLE
Propegating touch events from html pages

### ISSUE THREAD

**Issue by vongohren** [iberezansky/flip-book-jquery#1]
Hi im struggeling with touch events when im using the minified filed, becaues then touch seems to be enabled by default and that fucks up the propegation of htlm pages inside the reader.

But I change to the not minified file and then I could not swipe pages, but links works fine.

Do you have a suggestion to what to do to be able to have links and swipe work for the min file?

I have just worked with this a couple of hours now so just seeking advice from someone who have used it more than me!

**Comment by iberezansky** [comment]
Hi!

Could you explain what is 'minified file'? Do you use HTML pages as the
sources for a book?

Best regards,
Ivan.


On Dec 24, 2017 6:12 PM, "Snorre Lothar von Gohren Edwin" <
notifications@github.com> wrote:

Hi im struggeling with touch events when im using the minified filed,
becaues then touch seems to be enabled by default and that fucks up the
propegation of htlm pages inside the reader.

But I change to the not minified file and then I could not swipe pages, but
links works fine.

Do you have a suggestion to what to do to be able to have links and swipe
work for the min file?

I have just worked with this a couple of hours now so just seeking advice
from someone who have used it more than me!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/iberezansky/flip-book-jquery/issues/1>, or mute the
thread

**Comment by vongohren** [comment]
Hey, the minified file is the .min.js version of the file.

<img width="285" alt="screen shot 2017-12-27 at 08 22 08" src="https://user-images.githubusercontent.com/1012055/34374097-7aa3aace-eadf-11e7-93a5-40fa4d9523fc.png">

These three versions of the file have different default settings and works differently. The minified file has so it cannot be dragged around and you can touch drag pages. But this creates troubles for the touch event to be propegated.

I have sent you the archive books on email.

**Comment by vongohren** [comment]
Not using anymore, closing

**Comment by iberezansky** [comment]
Hi there!

We share with you free version of our plugin
http://url6652.creators.gumroad.com/ls/click?upn=56j1UXPh1eye3mggAaGeSnpE4V38HBXy4ItD-2BLnkXarMmxp4W7mOEFKPV5gyCc5BJ5b3_U31jt5HgHBh7k3Grc5s4l3bsb0zdGDulD-2FOaP8IQjccHcMGZoKg1Sk1trDT-2Bm1v7Z4q-2F-2FJijDucGEVAir3gu6w9kbdRBLvhxxNOW-2BbRZP4Bw8liwU7Mb5wtNoUDuvcW8C9NhAf57OAog6-2B8Fz8qasF5Fhxv7kkP-2BeuUWaKIEyv0HsWWyH71KyemQlD5BxQaaQ-2B14Ro9Jwx6L30ljhdtDr0BQtDC8u16stBgRKbKKLRKIMpmwu4EH-2B8Z6yClI77ZnyB-2FCyiLqOG-2BInXJX47c7t5Zp7YZH-2B6unDTThCn8VDVly-2B9rGRbI1waZVnk38NcIQ8897fadySAlcBf4GVD0Rjs9buOkllNMeLUPWlgGA3631gLXOOj3c3Z68lb4KOE-2BPgV-2FhEOv09M1VLxDdgSeLr5-2BsdvznGQiNe5yvNyB-2BG727qbFYzymxsHlzbnDp8qLq9dpC-2BP0-2BG-2FAXIrxv-2FThqFTAHMNEK9DCgHTyGHO-2FnGnJWkE-2BVYSbAIMXe9eRBhShLqmJtXW4xDTV-2FRH6IwBoBNT8c19tdHVBzomaSjmah69FcpF2ykdwpmerPpMKjz-2B-2BWkrNFQ7aLKGmGi5hNmdem7d-2Fl1iWzeGOwZ1CxCKhYUqauMbNliV8nlQAHsyqZ3evoE1VTOmzvj0NXUnp-2BUnTHvw-3D-3D You can use it in any projects!We need
your help in promo

-----------------------------
Free PDF viewer for Your site
-----------------------------

Hi there!

We share with you free version of our plugin
http://url6652.creators.gumroad.com/ls/click?upn=56j1UXPh1eye3mggAaGeSuRQrCp2WjB5D1zu-2Bu-2BXtbo-3DM9fN_U31jt5HgHBh7k3Grc5s4l3bsb0zdGDulD-2FOaP8IQjccHcMGZoKg1Sk1trDT-2Bm1v7Z4q-2F-2FJijDucGEVAir3gu6w9kbdRBLvhxxNOW-2BbRZP4Bw8liwU7Mb5wtNoUDuvcW8C9NhAf57OAog6-2B8Fz8qasF5Fhxv7kkP-2BeuUWaKIEyv0HsWWyH71KyemQlD5BxQaaQ-2B14Ro9Jwx6L30ljhdtDr0BQtDC8u16stBgRKbKKLRKIMpmwu4EH-2B8Z6yClI77ZnyB-2FCyiLqOG-2BInXJX47c7t5Zp7YZH-2B6unDTThCn8VDVly-2B9rGRbI1waZVnk38NcIQ8897fadySAlcBf4GVD0Rjs9buOkllNMeLUPWlgGA362910IY3GZ7qNJ0LsoDVsvfJvwbsaqqF2U2dr0MSkLTrhI-2B1ZHM6lyX-2BV-2FdDlpk1-2FkfNwb2cU-2Flto8iR-2BidaqQ2MBf8MzSacKoywus3IBEBii91h58y4gqLQnnK5t5TI-2FEPdh6qQceXCFoZk8SvBJ-2F9-2BRCWCB-2FCdN-2F-2F3SGxIMfAERvVxWjGqg1WG9ZiSZA1YHUs9f-2FafpcUTsKqf-2FC0thgTMQG9ptrhhPhLurYdPZV0QkGVM-2FIyh-2FBmbp2NKWmSb0yOamhiC0U-2B9WsMZV4N24sYOoaTpaodS6L5-2BJO2Y1qAYA-3D-3D ( http://url6652.creators.gumroad.com/ls/click?upn=56j1UXPh1eye3mggAaGeSnRerDBB5zCpiuClPUH2INFCTNXF7R5SyDMcKTCWj815jjoL_U31jt5HgHBh7k3Grc5s4l3bsb0zdGDulD-2FOaP8IQjccHcMGZoKg1Sk1trDT-2Bm1v7Z4q-2F-2FJijDucGEVAir3gu6w9kbdRBLvhxxNOW-2BbRZP4Bw8liwU7Mb5wtNoUDuvcW8C9NhAf57OAog6-2B8Fz8qasF5Fhxv7kkP-2BeuUWaKIEyv0HsWWyH71KyemQlD5BxQaaQ-2B14Ro9Jwx6L30ljhdtDr0BQtDC8u16stBgRKbKKLRKIMpmwu4EH-2B8Z6yClI77ZnyB-2FCyiLqOG-2BInXJX47c7t5Zp7YZH-2B6unDTThCn8VDVly-2B9rGRbI1waZVnk38NcIQ8897fadySAlcBf4GVD0Rjs9buOkllNMeLUPWlgGA362-2BHFxWaTkKVLLxdEq2BSKNjFJ-2Ft3t2sDtKFT-2BIF36iJJoG5fQ6LN38-2BcuO5g7iGkYrq-2B9fY94JSSoNiT7DUw64drgf8Zd3h0BUH0e4zYOxOYa-2F6XxzHrVApACZJFugKyDvq-2Fb3EBnyT9Rn8CfDkHhn0nKu19vPT4vzA7NsFV2eebqLLu8XVgtAsWs8YOg-2BtK0aLVuD8Pu-2B-2Bl1IZlER35MnRizkQpSqXMcPbpsuW49hnwrtNR1ReaPwWn9klgLhT-2BLxMxr54Q7tbIP5NSnf0Le-2FPZ89dpapcWZPe814idUhYQ-3D-3D ).
You can use it in any projects!

We need your help in promotion, so if you like this, give us
thumbs up and subscribe for next campaigns.

All the best,

3D FlipBook Team.

Download 
( http://url6652.creators.gumroad.com/ls/click?upn=56j1UXPh1eye3mggAaGeSjLE1bd9VFliUaDFepiiQo8TitmYQFcoyOjtFnZnBes3bp7pElfVyrKllUks-2BLNFKr75BS-2B5GLdnJdaTwQ7fA5QVt5UIIZkbkRGyr5-2BkwKowiRWS_U31jt5HgHBh7k3Grc5s4l3bsb0zdGDulD-2FOaP8IQjccHcMGZoKg1Sk1trDT-2Bm1v7Z4q-2F-2FJijDucGEVAir3gu6w9kbdRBLvhxxNOW-2BbRZP4Bw8liwU7Mb5wtNoUDuvcW8C9NhAf57OAog6-2B8Fz8qasF5Fhxv7kkP-2BeuUWaKIEyv0HsWWyH71KyemQlD5BxQaaQ-2B14Ro9Jwx6L30ljhdtDr0BQtDC8u16stBgRKbKKLRKIMpmwu4EH-2B8Z6yClI77ZnyB-2FCyiLqOG-2BInXJX47c7t5Zp7YZH-2B6unDTThCn8VDVly-2B9rGRbI1waZVnk38NcIQ8897fadySAlcBf4GVD0Rjs9buOkllNMeLUPWlgGA363-2BQ9yUxM7rrgpNd8YeNSFhKVKG7lK0nkop8WfFKZQvxLM8CrBy2M3C259CRSS1cAAegPQZ-2FBn9WGoFTzZLeSMye-2Fd3mJXsyoZraRm23M18B506gkvq8kBw3tFFfFgqD6PeCzfXtFU1J6DhMmP3RXd0PZXsW0dP25Ufzx-2FYez93a-2B3qHxUGTfOndaTAwCAZ0hsDgIKIMIUW-2FbXzECwrdPh7AaqZ72ef2gMFfQR30g1sKkpzLhmURGDv5j8ubDyWveAyDzUFKLeNlsTzpvAvasgZ8kpHoSpqMC3jil8NkQ74bQ-3D-3D )


Unsubscribe 
( http://url6652.creators.gumroad.com/ls/click?upn=56j1UXPh1eye3mggAaGeShD1-2FlVeyzX2XF4-2BgBMhMrSvelpjCqGVrEIySp2xp6BKw2-2FusFPs-2Fr8uEgtiCLV5yn0yXyQKSpV8tZCxv26Nx-2Fc-3DQc9C_U31jt5HgHBh7k3Grc5s4l3bsb0zdGDulD-2FOaP8IQjccHcMGZoKg1Sk1trDT-2Bm1v7Z4q-2F-2FJijDucGEVAir3gu6w9kbdRBLvhxxNOW-2BbRZP4Bw8liwU7Mb5wtNoUDuvcW8C9NhAf57OAog6-2B8Fz8qasF5Fhxv7kkP-2BeuUWaKIEyv0HsWWyH71KyemQlD5BxQaaQ-2B14Ro9Jwx6L30ljhdtDr0BQtDC8u16stBgRKbKKLRKIMpmwu4EH-2B8Z6yClI77ZnyB-2FCyiLqOG-2BInXJX47c7t5Zp7YZH-2B6unDTThCn8VDVly-2B9rGRbI1waZVnk38NcIQ8897fadySAlcBf4GVD0Rjs9buOkllNMeLUPWlgGA360BDGPmVPs3TUqfGB-2BHDBm1g-2BjDx5s54G8S4TF-2BJbEJFYPi3Ra9oa0hzJrDJloc-2FNeTPdttYMjU4oE3xROsSYJp7wJV0Krf6dc-2FXlld2WsjogfSywvaBKkmhel12fPuevEtTNJiG-2F0JIhG3cgi17DmIRialBaKOcYt-2FokhxeX-2F6oh0j1yUy3xYw8bNkDtJ7pWXkPQZgo-2Bo2wAoSw6DL3JzvDs0CYuf-2FwxByyxuwPbBSLJnc3p5bPQnk8R-2FghHJjQuFQblAQZ4IxiQmCtD3U03vwnQq7ECLOFrOdtIB7g4enMg-3D-3D )

548 Market St, San Francisco, CA 94104-5401, USA

**Comment by vongohren** [comment]
Started hacking now! :D
