### ISSUE TITLE
iOS problems on render HTML

### ISSUE THREAD

**Issue by vongohren** [iberezansky/flip-book-jquery#2]
Im trying to do 5 pages og img and one page of html. But what happens on iOS is that the html page turns black. I have reported this here: https://github.com/mrdoob/three.js/issues/9754#issuecomment-353866100

But maybe @iberezansky you know a little better what might be wrong? Or where this error might be?

This is also related: https://github.com/tsayen/dom-to-image/issues/74

```
pageCallback: function(n) {
      if(n==totalPages-1) {
          return {
              type: 'html',
              src: 'src/'+location.hash.substr(1)+'/doodle.html',
              interactive: true
           };
       }
       return {
           type: 'image',
           src: 'src/'+location.hash.substr(1)+'/img-'+(n+1)+'.png',
           interactive: false
       }
};
```

**Comment by iberezansky** [comment]
Hi!

could you send to me your test book in archive? iwill research the problem.

best regards,
Ivan.

**Comment by vongohren** [comment]
Here are the archive books: [archive.zip](https://github.com/iberezansky/flip-book-jquery/files/1588536/archive.zip)

Total pages of 5, with one back side of the page.

I have been able to get the wanted effect by using the example you of loading video in the page. Then I just load a full size html page over an image. But why that works, and not this one above, im not sure.

**Comment by vongohren** [comment]
Not usin anymore, closing

**Comment by iberezansky** [comment]
Hi there!

We share with you free version of our plugin
http://url6652.creators.gumroad.com/ls/click?upn=56j1UXPh1eye3mggAaGeSnpE4V38HBXy4ItD-2BLnkXarMmxp4W7mOEFKPV5gyCc5BmR27_U31jt5HgHBh7k3Grc5s4l4uoH4XPD4A91HWFaRuwIHCkQd2VEDrAEashhdbQ4q5mZdTsG0X8oGqx1AXaNFb-2BhE1GxrvuRKOeWjHqbbNEezV0dXAm-2BtoFVhLVVw5kibloKGvxyWXkQyI4XWOteXTtYCb0VsFrlf3LPGXjVJEDyfmNYHausCjSV-2Fz-2Fkw3LkbVj2AvojJqP1npz3PWHubVmweELbIGucWsNyyxEZ8enCXpSC-2BHhisXV24Y9-2F5glSc2csJEkOzADL-2FByCL3GDPajcU1aMIGO9xmGygpS7lEHwFtuX7c7QoaGSxy0Ls05GMYVzj5f9nEud-2BlqTof11VQedgDU6lRsJTyQMyVDR-2FzNwYFa3-2B3ysYCYT1k-2BsDJ8VlGUYOkLbJPAgbrj10ecZfMBX697vYhJaFbx6kev6O4hCdBgT0Ty2V3ubrwW0-2FaCER-2BJPEwfw15qyzugXqmQ7ScoC77CBZeX1PYABQ2zXIPBqMhKH-2FXD0V60YSeuag0qjJfkR-2B9b3Ll38yGIs2dHHC4oUYWAK-2BY6LnY-2B9E5S-2BTcVID8wulYPlQP3xNGbsiM8krcxvYCElwLGBFPNmM9TkRUZSlEPrU-2F1XY8hGtC6wOFVVRNXAdVRYiCwrBsZ-2BTqosagOn63iMb7wYDAjVf-2FgBSlkOw-3D-3D You can use it in any projects!We need
your help in promo

-----------------------------
Free PDF viewer for Your site
-----------------------------

Hi there!

We share with you free version of our plugin
http://url6652.creators.gumroad.com/ls/click?upn=56j1UXPh1eye3mggAaGeSuRQrCp2WjB5D1zu-2Bu-2BXtbo-3DOOJD_U31jt5HgHBh7k3Grc5s4l4uoH4XPD4A91HWFaRuwIHCkQd2VEDrAEashhdbQ4q5mZdTsG0X8oGqx1AXaNFb-2BhE1GxrvuRKOeWjHqbbNEezV0dXAm-2BtoFVhLVVw5kibloKGvxyWXkQyI4XWOteXTtYCb0VsFrlf3LPGXjVJEDyfmNYHausCjSV-2Fz-2Fkw3LkbVj2AvojJqP1npz3PWHubVmweELbIGucWsNyyxEZ8enCXpSC-2BHhisXV24Y9-2F5glSc2csJEkOzADL-2FByCL3GDPajcU1aMIGO9xmGygpS7lEHwFtuX7c7QoaGSxy0Ls05GMYVzj5f9nEud-2BlqTof11VQedgDU6lRsJTyQMyVDR-2FzNwYFNzjKmsiEGkfsoBDDB7B3T3tvONgGKkbWdb1N9miO8OthvddPZI4pqMgAYurnQTOPY-2BTwVPfDlgFbPuap4IUrsv0nxWhSPASQYsgUd-2FRYPsZOgW-2FyNxfB2v-2F-2Fm-2BY-2BiPVEthBAEy9GyTw4VFJUDIz5qmQOZQ6bG1A41pkyNRYSoDmMxfLiMWmyDu1MhuborVEf-2BKL1BS5QAXe9bsBRPgJJop1fwQlTCpu6lgphB-2FJuCKG4Imzi4SzVCrntnCRWm-2BPgqv1EzRjlrQkpvIyeilppnse9Hi3-2Fkv1vw-2FI5AhneD-2Fw-3D-3D ( http://url6652.creators.gumroad.com/ls/click?upn=56j1UXPh1eye3mggAaGeSnRerDBB5zCpiuClPUH2INFCTNXF7R5SyDMcKTCWj815Tilk_U31jt5HgHBh7k3Grc5s4l4uoH4XPD4A91HWFaRuwIHCkQd2VEDrAEashhdbQ4q5mZdTsG0X8oGqx1AXaNFb-2BhE1GxrvuRKOeWjHqbbNEezV0dXAm-2BtoFVhLVVw5kibloKGvxyWXkQyI4XWOteXTtYCb0VsFrlf3LPGXjVJEDyfmNYHausCjSV-2Fz-2Fkw3LkbVj2AvojJqP1npz3PWHubVmweELbIGucWsNyyxEZ8enCXpSC-2BHhisXV24Y9-2F5glSc2csJEkOzADL-2FByCL3GDPajcU1aMIGO9xmGygpS7lEHwFtuX7c7QoaGSxy0Ls05GMYVzj5f9nEud-2BlqTof11VQedgDU6lRsJTyQMyVDR-2FzNwYFergNZqXfUIoe0Qk4182gS-2FaG4xQDF3zLdvYFIp0Hm-2Bn15gF-2BM67asp5z7UNkhoMNQSWc5oNtHr7K-2BD5HsCefcabdkJFsUO9WuTcsMiA-2BAe5zEaa1pYNUcNRaTquqxz60cD8kPbOMMIj-2BJzOKLXDDpjrCTJtiQxgyv7HakkNWRShe-2F8CD8eeg6BRQYEi3DgcGdOSuB6irPzH9P-2BhSdZ9ZmptGk1gjIkPBaG9J3RWc1BhTIebdavbu2xtpiW9i0AhbPIXVJiQzr1ckCxoHebNXN6mfp4cP-2FGm8haKgHg7XFbw-3D-3D ).
You can use it in any projects!

We need your help in promotion, so if you like this, give us
thumbs up and subscribe for next campaigns.

All the best,

3D FlipBook Team.

Download 
( http://url6652.creators.gumroad.com/ls/click?upn=56j1UXPh1eye3mggAaGeSjLE1bd9VFliUaDFepiiQo8TitmYQFcoyOjtFnZnBes3bp7pElfVyrKllUks-2BLNFKr75BS-2B5GLdnJdaTwQ7fA5QVt5UIIZkbkRGyr5-2BkwKowBUXo_U31jt5HgHBh7k3Grc5s4l4uoH4XPD4A91HWFaRuwIHCkQd2VEDrAEashhdbQ4q5mZdTsG0X8oGqx1AXaNFb-2BhE1GxrvuRKOeWjHqbbNEezV0dXAm-2BtoFVhLVVw5kibloKGvxyWXkQyI4XWOteXTtYCb0VsFrlf3LPGXjVJEDyfmNYHausCjSV-2Fz-2Fkw3LkbVj2AvojJqP1npz3PWHubVmweELbIGucWsNyyxEZ8enCXpSC-2BHhisXV24Y9-2F5glSc2csJEkOzADL-2FByCL3GDPajcU1aMIGO9xmGygpS7lEHwFtuX7c7QoaGSxy0Ls05GMYVzj5f9nEud-2BlqTof11VQedgDU6lRsJTyQMyVDR-2FzNwYEs1u4Ypaf2ULVkSmiBBS0TOLNfxNGT2AMDF3tP7G25nQqabG-2Bf2LNVHryyU79sHxgYzlFXkzc4X9bRoeGtLBhx1-2B-2FL9PjO3IFXFluwrMhJz5LNyHdtNGmDEbedNBXvT7JkPMJs7s-2BeSwHBVU8wUnbFt8fXLlTOiSrLYJMiPgBWZrzDqN8Qp-2B-2Fx3MrvkQ6zAc8SEgo7ApdwQ3T7r8ISqFpLWe-2BsVSv-2Fpt6tSgLmkPHvhMHF535ztsn-2Fe2cunMPKWrPVBQ4FmHooOKhrV8P9rKGaXUUzL8mvrNcTwBQH5RR-2BwQ-3D-3D )


Unsubscribe 
( http://url6652.creators.gumroad.com/ls/click?upn=56j1UXPh1eye3mggAaGeShD1-2FlVeyzX2XF4-2BgBMhMrSe9VVG8wdq0mSrEGyvX7UjI3djCPcE6G1mtusGMKU168bbQYGif5QcXKd-2B2GrrDj4-3D6yyl_U31jt5HgHBh7k3Grc5s4l4uoH4XPD4A91HWFaRuwIHCkQd2VEDrAEashhdbQ4q5mZdTsG0X8oGqx1AXaNFb-2BhE1GxrvuRKOeWjHqbbNEezV0dXAm-2BtoFVhLVVw5kibloKGvxyWXkQyI4XWOteXTtYCb0VsFrlf3LPGXjVJEDyfmNYHausCjSV-2Fz-2Fkw3LkbVj2AvojJqP1npz3PWHubVmweELbIGucWsNyyxEZ8enCXpSC-2BHhisXV24Y9-2F5glSc2csJEkOzADL-2FByCL3GDPajcU1aMIGO9xmGygpS7lEHwFtuX7c7QoaGSxy0Ls05GMYVzj5f9nEud-2BlqTof11VQedgDU6lRsJTyQMyVDR-2FzNwYFQV9kt-2Fwm1LBrEaNYYe3hXg2V9hWMq9D58YyRvX9UoN-2BpC8LguXWI1n5nsysSVFXzL89yiGBn-2BfBHgcioGFFr1rzaYTILsJ3QYKsP5kGibyDipnQCv2qg6zLE1j-2Fbus1kkcft4WpMONkqUN45X5gtmPDpZKI6JNIvt-2FsWufr-2FMHdFl8lIKyejzLnK8EVgLvRlJ3-2FFVCR-2B6bUr2KSI4yT03y2eacTW6ZLtE4NvukX3K6VFz63RkrDNBVdxAd-2FC4P2Si8BFTK-2BcqxB2kpLjlhAHzzBmEZQ9nZ7ngWfTI4OcoWw-3D-3D )

548 Market St, San Francisco, CA 94104-5401, USA
