### ISSUE TITLE
Using With Angular 5

### ISSUE THREAD

**Issue by matheusAle** [iberezansky/flip-book-jquery#5]
Hello,
I'm trying to use the 3d-flip-book with the angular 5 but I always get this error in the console:
flip-book.js:7197 Uncaught TypeError: frontGeometry.translate is not a function
    at Object.eval (flip-book.js:7197)
    at __webpack_require__ (flip-book.js:20)
    at Object.eval (flip-book.js:901)
    at __webpack_require__ (flip-book.js:20)
    at Object.eval (flip-book.js:5532)
    at __webpack_require__ (flip-book.js:20)
    at Object.eval (flip-book.js:3406)
    at __webpack_require__ (flip-book.js:20)
    at Object.eval (flip-book.js:2786)
    at __webpack_require__ (flip-book.js:20)
(anonymous) @ flip-book.js:7197
__webpack_require__ @ flip-book.js:20
(anonymous) @ flip-book.js:901
__webpack_require__ @ flip-book.js:20
(anonymous) @ flip-book.js:5532
__webpack_require__ @ flip-book.js:20
(anonymous) @ flip-book.js:3406
__webpack_require__ @ flip-book.js:20
(anonymous) @ flip-book.js:2786
__webpack_require__ @ flip-book.js:20
(anonymous) @ flip-book.js:12591
__webpack_require__ @ flip-book.js:20
(anonymous) @ flip-book.js:66
(anonymous) @ flip-book.js:69
../../../../3d-flip-book/dist/flip-book.js @ vendor.bundle.js:6
__webpack_require__ @ inline.bundle.js:55
(anonymous) @ app.component.ts:3
../../../../../src/app/app.component.ts @ main.bundle.js:28
__webpack_require__ @ inline.bundle.js:55
(anonymous) @ app.module.ts:5
../../../../../src/app/app.module.ts @ main.bundle.js:36
__webpack_require__ @ inline.bundle.js:55
(anonymous) @ main.ts:4
../../../../../src/main.ts @ main.bundle.js:52
__webpack_require__ @ inline.bundle.js:55
0 @ main.bundle.js:67
__webpack_require__ @ inline.bundle.js:55
webpackJsonpCallback @ inline.bundle.js:26
(anonymous) @ main.bundle.js:1

**Comment by sureshkodur** [comment]
@matheusAle , Can you please help me, how to integrate it with angular 5 or above. Thanks in advance
