### ISSUE TITLE
single page view mode in Desktop

### ISSUE THREAD

**Issue by gauravAbs** [iberezansky/flip-book-jquery#7]
how to use single page view mode in desktop.i am waiting for your reply,
thanks

**Comment by iberezansky** [comment]
Hi,

Enable it by default in the plugin settings->actions->cmdSinglePage

Best regards,
Ivan.

**Comment by iberezansky** [comment]
Hi there!

We share with you free version of our plugin
http://url6652.creators.gumroad.com/ls/click?upn=56j1UXPh1eye3mggAaGeSnpE4V38HBXy4ItD-2BLnkXarMmxp4W7mOEFKPV5gyCc5BTW0w_U31jt5HgHBh7k3Grc5s4l-2B4mSswsCXt-2BOiEDPTkHFrLqLgMqlNM4-2FifN-2B17WfRs0ndpGb9NwCnmrDOwJv8U7B0LNBqpv562CIwVbYjo5dS3G70pofhorEUquII1RicqIm6fUoJoM5cSf2pB-2FQmw5LEg19oy4R2ncRlzyV6Ju2F0t8Qd3LtrV5VfebmR5hMkJ1eyAgNa2ch2Wonle-2FfuYFRpzHCh67W0LUC0doJU2KurkMlxJKRRLNgr-2BXerTrpn-2FqgLx-2Ft6oaBkKN5wyxR4C7F8qg2fx77wvnLNpde6yMj8-2BFHDfSibPI9dEZZ4AGHw9dj2YvITzLFyv7qhrDdzNm4Ab2QK-2FW7ZWLToGQceQw3lvcOW6w1Wnvz4Tn73op-2BwSNF2bxU9gd-2FVx3WOpNLIqGw40rSIBnI0No4e6R9djNo94Dfh6x1DqXfArj6dHI07XIimnFMZUv1qdWTpJNIbB78p4-2FBLTPCtm2hIAy6VPxwXrowTTfIRDr0ihthcU2TYcWeL-2FRlSu1VbFnov59tDN4-2FiplUSFWFqvHIGUWIwMPDijo59vkuN37mVf43WvDYlNfwiXl7yjanIN5GrfgKc1Bndys7RtUaaPRZb8C-2BJkbdVhbT-2FGpDaL2DEvdSb-2F5uMnFf2W2lo8SZxzY7PCGBy9uA-3D-3D You can use it in any projects!We need
your help in promo

-----------------------------
Free PDF viewer for Your site
-----------------------------

Hi there!

We share with you free version of our plugin
http://url6652.creators.gumroad.com/ls/click?upn=56j1UXPh1eye3mggAaGeSuRQrCp2WjB5D1zu-2Bu-2BXtbo-3DDOaX_U31jt5HgHBh7k3Grc5s4l-2B4mSswsCXt-2BOiEDPTkHFrLqLgMqlNM4-2FifN-2B17WfRs0ndpGb9NwCnmrDOwJv8U7B0LNBqpv562CIwVbYjo5dS3G70pofhorEUquII1RicqIm6fUoJoM5cSf2pB-2FQmw5LEg19oy4R2ncRlzyV6Ju2F0t8Qd3LtrV5VfebmR5hMkJ1eyAgNa2ch2Wonle-2FfuYFRpzHCh67W0LUC0doJU2KurkMlxJKRRLNgr-2BXerTrpn-2FqgLx-2Ft6oaBkKN5wyxR4C7F8qg2fx77wvnLNpde6yMj8-2BFHDfSibPI9dEZZ4AGHw9dj2YvITzLFyv7qhrDdzNm4Ab2QK-2FW7ZWLToGQceQw3kOI7JhmTbpO65dqPyWGsMS2zcP4zt372GAuQJ5JoMC16nep9q0ZdTIAHsuy-2FtjbkxLsaJDbVUBrLUWYxa8xsoxDQT8yNJywbsXK6khQaiI5PyoAAcZldqQS-2FGzu-2B4fThPxJRx13RVb2B7pRSs4y-2BfqITTxNukT54Kv1dRKkJ0iDQTZtQk-2Bt0jCKplcHAaTbEgCufI94bDjr9Ikgd2qgHtpA8L9xpjzt5W7pcEyFtVMKeROiQvWCjvyZwW9LbNSvoY1e4d3fY22ASCjS-2BabIbXCGx-2FjJjijuxAwaai9m8RCvQ-3D-3D ( http://url6652.creators.gumroad.com/ls/click?upn=56j1UXPh1eye3mggAaGeSnRerDBB5zCpiuClPUH2INFCTNXF7R5SyDMcKTCWj815V-rG_U31jt5HgHBh7k3Grc5s4l-2B4mSswsCXt-2BOiEDPTkHFrLqLgMqlNM4-2FifN-2B17WfRs0ndpGb9NwCnmrDOwJv8U7B0LNBqpv562CIwVbYjo5dS3G70pofhorEUquII1RicqIm6fUoJoM5cSf2pB-2FQmw5LEg19oy4R2ncRlzyV6Ju2F0t8Qd3LtrV5VfebmR5hMkJ1eyAgNa2ch2Wonle-2FfuYFRpzHCh67W0LUC0doJU2KurkMlxJKRRLNgr-2BXerTrpn-2FqgLx-2Ft6oaBkKN5wyxR4C7F8qg2fx77wvnLNpde6yMj8-2BFHDfSibPI9dEZZ4AGHw9dj2YvITzLFyv7qhrDdzNm4Ab2QK-2FW7ZWLToGQceQw3mAczHw-2Fu3ORKjsJ2NKmdZzkDrETS2xk7wqgj389mZ2nYOxfNg-2BuIgR2C-2BAh3yac1Y4oIGod2SiI8D88TTY4V2Qf5OeAXm1XrL1I3NqEJPMyvWXIjrnC486At7sAeLmBpefdiUFcs3a-2FL3dfuGgwbkFjogmUgmAP-2F-2F-2BKyKjVjeoDGKd7cGombmIG4t4amqMmckU-2FLV0gVKRwBzjUCTC-2BVg60DCVCWrU5gM0TtIW-2Fwf-2BA1rd5Ls4iiLbxV8cD8Cu9sXRs-2BQWzqA1L4SqYQQYcwhmHpCbJuORBTyHCKOTPLNqhw-3D-3D ).
You can use it in any projects!

We need your help in promotion, so if you like this, give us
thumbs up and subscribe for next campaigns.

All the best,

3D FlipBook Team.

Download 
( http://url6652.creators.gumroad.com/ls/click?upn=56j1UXPh1eye3mggAaGeSjLE1bd9VFliUaDFepiiQo8TitmYQFcoyOjtFnZnBes3bp7pElfVyrKllUks-2BLNFKr75BS-2B5GLdnJdaTwQ7fA5QVt5UIIZkbkRGyr5-2BkwKows4SM_U31jt5HgHBh7k3Grc5s4l-2B4mSswsCXt-2BOiEDPTkHFrLqLgMqlNM4-2FifN-2B17WfRs0ndpGb9NwCnmrDOwJv8U7B0LNBqpv562CIwVbYjo5dS3G70pofhorEUquII1RicqIm6fUoJoM5cSf2pB-2FQmw5LEg19oy4R2ncRlzyV6Ju2F0t8Qd3LtrV5VfebmR5hMkJ1eyAgNa2ch2Wonle-2FfuYFRpzHCh67W0LUC0doJU2KurkMlxJKRRLNgr-2BXerTrpn-2FqgLx-2Ft6oaBkKN5wyxR4C7F8qg2fx77wvnLNpde6yMj8-2BFHDfSibPI9dEZZ4AGHw9dj2YvITzLFyv7qhrDdzNm4Ab2QK-2FW7ZWLToGQceQw3mxcJlz-2FAuBizPGHsarl-2Bj9Vc41ugcUrCo9t-2F29-2FwglquPJ-2FfBd5b3UWnqUwSov-2BcHopkPR95xVtgLqcTj0CMnj9Lq-2FF-2FVYzmFs1ISO5p5PeMa8-2FU2rNF-2BAAtW19Qk-2FMKYJniL2uL4edTzrafbdUbt02AS4ZfTOiiXVHUmnETaypRPW6KlF1qBQcWqyfHuPJOmZ4J86Buxd12WSQaHMLmv2Bo-2FE74N0DTDHq4aPKiCMVaInkRGfZs5nQs8wVZvTbTBA7gn-2BjMcDe1NpamBXZMXdFnxGQCcdJ3eSTiM6PLjTBg-3D-3D )


Unsubscribe 
( http://url6652.creators.gumroad.com/ls/click?upn=56j1UXPh1eye3mggAaGeShD1-2FlVeyzX2XF4-2BgBMhMrSN-2Fkr912yBTd7VFtMntxVeYJTc7FFxVer-2FSeE9oHE2sOEEVFhRQuFGWJqh8XGjMwY-3DLS_s_U31jt5HgHBh7k3Grc5s4l-2B4mSswsCXt-2BOiEDPTkHFrLqLgMqlNM4-2FifN-2B17WfRs0ndpGb9NwCnmrDOwJv8U7B0LNBqpv562CIwVbYjo5dS3G70pofhorEUquII1RicqIm6fUoJoM5cSf2pB-2FQmw5LEg19oy4R2ncRlzyV6Ju2F0t8Qd3LtrV5VfebmR5hMkJ1eyAgNa2ch2Wonle-2FfuYFRpzHCh67W0LUC0doJU2KurkMlxJKRRLNgr-2BXerTrpn-2FqgLx-2Ft6oaBkKN5wyxR4C7F8qg2fx77wvnLNpde6yMj8-2BFHDfSibPI9dEZZ4AGHw9dj2YvITzLFyv7qhrDdzNm4Ab2QK-2FW7ZWLToGQceQw3mqPYEWvnW6QEibOb-2Fu6N4RB0yN7y4HZzNpRcSS19Yffr8l9lQXyHWj8XRr-2F3fSoIC7GOeS1i-2Bw8ucbxSTVSEgwHM1wRSFhE5MfvlmsrcyRDPv2OLVIZvFcWXw09wEWH2i4wsiETMvUPIq-2Fx6bI-2FNMOAOgFkbjH4cvRWvowFhigIfUwwvZS7qjt32mqpZFPbindq7uWPeUiH1rE-2FOYDffwD5JbjJEfqSnMVnJefBP3VUlxrsYjaUBaLAc2RpCmvbK-2FN7IJbEl7dtWiVyajLAC2-2FkeVge0Mzbl-2BcwMdlgdCFPw-3D-3D )

548 Market St, San Francisco, CA 94104-5401, USA
